#include <stdio.h>
#include <stdlib.h>
#include "ir.h"
#include "parser.h"
#include "lexer.h"

/* given a token, read the area in the file it points to into a newly allocated
 * null terminated string and return it */
static char *token_to_string(struct lex_state *state, struct token *t) {
    char *string;
    unsigned int len, len2;

    len = t->file_end - t->file_start;
    string = (char *) malloc(len + 1);
    if (string == NULL) {
        perror("failed to allocate memory");
        exit(1);
    }

    fseek(state->stream, t->file_start, SEEK_SET);
    if ((len2 = fread(string, 1, len, state->stream)) != len) {
        free(string);
        return NULL;
    }
    string[len] = 0;

    return string;
}

/* given a token, read the area in the file it points to and parse it into a
 * number of the given base, up to base 16 */
/* TODO: add binary notation (0b...) support since it'll be easy */
static unsigned long parse_number(struct lex_state *state, struct token *t,
                                  unsigned long base) {
    unsigned long result = 0;
    unsigned int len, len2, i = 0;
    char c;

    len = t->file_end - t->file_start;

    fseek(state->stream, t->file_start, SEEK_SET);

    for (; i < len; i ++) {
        if (!fread(&c, 1, 1, state->stream))
            lex_error(state, "what the fuck");

        result *= base;

        if (isdigit(c))
            result += c - '0';
        else if (c >= 'a' && c <= 'f')
            result += c - 'a' + 10;
        else if (c >= 'A' && c <= 'F')
            result += c - 'A' + 10;
    }

    return result;
}

static struct struct_union_field *parse_struct_union(struct lex_state *state);

/* error messages that can be generated by parse_standard_type() */
const char *dup_type_spec_err = "duplicate type specifier";
const char *dup_storage_err = "duplicate storage class";
const char *dup_sign_err = "duplicate sign specifier";
const char *dup_type_qual_err = "duplicate type qualifier";
const char *no_type_spec = "expected type specifier";
const char *missing_name_def = "expected identifier or `{'";

/* macros to deduplicate wacky code in parse_standard_type() */

/* set the type specifier to the given type specifier, set the
 * have_type_specifier flag, and throw an error if a type specifier has already
 * been set */
#define SET_TYPE_SPECIFIER(t) {\
    if (have_type_specifier)\
        lex_error(state, dup_type_spec_err);\
    have_type_specifier = 1;\
    type_specifier = t;\
}
/* same as SET_TYPE_SPECIFIER() but with storage class. since there's a default
 * otherwise unobtainable value for storage class we don't need to set any flags
 */
#define SET_STORAGE_CLASS(c) {\
    if (storage_class != C_AUTO)\
        lex_error(state, dup_storage_err);\
    storage_class = c;\
}
/* same as SET_STORAGE_CLASS() but for sign specifier */
#define SET_SIGN_SPECIFIER(s) {\
    if (sign_specifier != S_UNKNOWN)\
        lex_error(state, dup_sign_err);\
    sign_specifier = s;\
}
/* parse struct name and/or fields */
#define PARSE_STRUCT_UNION(s) {\
    if (have_type_specifier)\
        lex_error(state, dup_type_spec_err);\
    if (!lex(state, &t))\
        lex_error(state, missing_name_def);\
    switch (t.kind) {\
        case T_IDENT:\
            if (lex(state, &t2))\
                if (t2.kind != T_OPEN_CURLY)\
                    lex_rewind(state);\
                else {\
                    /* TODO: store name and fields somewhere */\
                    first_field = parse_struct_union(state);\
                    have_fields = 1;\
                    break;\
                }\
            name = token_to_string(state, &t);\
            have_fields = 0;\
            break;\
        case T_OPEN_CURLY:\
            first_field = parse_struct_union(state);\
            have_fields = 1;\
            break;\
        default:\
            lex_error(state, missing_name_def);\
            break;\
    }\
    have_type_specifier = 1;\
    type_specifier = s;\
}

/* parses a "standard type" signature (i.e. anything in enum type_specifier)
 * and its storage class, sign specifier, and qualifiers. returns 1 on success,
 * 0 on failure. contents of the type pointer will only be modified on success
 */
static char parse_standard_type(struct lex_state *state, struct type *type) {
    struct token t, t2;
    char *name = NULL;
    enum type_specifier type_specifier;
    unsigned char have_type_specifier = 0;
    enum storage_class storage_class = C_AUTO;
    enum sign_specifier sign_specifier = S_UNKNOWN;
    unsigned char have_fields = 0;
    unsigned char const_qualified = 0;
    unsigned char volatile_qualified = 0;
    struct struct_union_field *first_field = NULL;
    unsigned int size = 0;

    while (1) {
        if (!lex(state, &t))
            break;

        switch (t.kind) {
            case T_VOID:
                SET_TYPE_SPECIFIER(TY_VOID);
                size = 0;
                continue;
            case T_CHAR:
                SET_TYPE_SPECIFIER(TY_CHAR);
                size = 1;
                continue;
            case T_SHORT:
                SET_TYPE_SPECIFIER(TY_SHORT);
                size = 2;
                continue;
            case T_LONG:
                if (have_type_specifier)
                    if (type_specifier == TY_LONG) {
                        type_specifier = TY_LONG_LONG;
                        size = 8;
                    } else
                        lex_error(state, dup_type_spec_err);

                have_type_specifier = 1;
                type_specifier = TY_LONG;
                size = 4;
                continue;
            case T_INT:
                if (have_type_specifier && type_specifier != TY_SHORT &&
                    type_specifier != TY_LONG && type_specifier != TY_LONG_LONG)
                    lex_error(state, dup_type_spec_err);

                have_type_specifier = 1;
                type_specifier = TY_INT;
                size = 2;
                continue;
            case T_EXTERN:
                SET_STORAGE_CLASS(C_EXTERN);
                continue;
            case T_STATIC:
                SET_STORAGE_CLASS(C_STATIC);
                continue;
            case T_UNSIGNED:
                SET_SIGN_SPECIFIER(S_UNSIGNED);
                continue;
            case T_SIGNED:
                SET_SIGN_SPECIFIER(S_SIGNED);
                continue;
            case T_CONST:
                if (const_qualified)
                    lex_error(state, dup_type_qual_err);
                else
                    const_qualified = 1;
                continue;
            case T_VOLATILE:
                if (volatile_qualified)
                    lex_error(state, dup_type_qual_err);
                else
                    volatile_qualified = 1;
                continue;
            case T_STRUCT:
                PARSE_STRUCT_UNION(TY_STRUCT);
                size = 0;
                if (have_fields && first_field != NULL) {
                    struct struct_union_field *field = first_field;

                    while (1)
                        if (field->next == NULL) {
                            size = field->offset + field->type.size;
                            break;
                        } else
                            field = field->next;
                }
                continue;
            case T_UNION:
                PARSE_STRUCT_UNION(TY_UNION);
                size = 0;
                if (have_fields && first_field != NULL) {
                    struct struct_union_field *field = first_field;

                    while (field != NULL) {
                        if (field->type.size > size)
                            size = field->type.size;

                        field = field->next;
                    }
                }
                continue;
            default:
                /* rewind the lexer to pass this token back to whatever called
                 * this function */
                lex_rewind(state);
                break;
        }

        break;
    }

    if (!have_type_specifier)
        if (storage_class == C_AUTO && sign_specifier == S_UNKNOWN &&
            !const_qualified && !volatile_qualified)
            return 0;
        else
            lex_error(state, no_type_spec);

    type->top_type = TOP_NORMAL;
    type->type.standard_type.type_specifier = type_specifier;
    type->type.standard_type.storage_class = storage_class;
    type->type.standard_type.sign_specifier = sign_specifier;
    type->type.standard_type.const_qualified = const_qualified;
    type->type.standard_type.volatile_qualified =
        volatile_qualified;
    if (type->type.standard_type.has_fields = have_fields)
        type->type.standard_type.name_field_ptr = first_field;
    else
        type->type.standard_type.name_field_ptr = name;
    type->size = size;

    return 1;
}

/* duplicates a type, safely allocating memory for it in the process */
static struct type *dup_type(struct type *type) {
    struct type *new;
    new = (struct type *) malloc(sizeof(struct type));
    if (new == NULL) {
        perror("failed to allocate memory");
        exit(1);
    }
    *new = *type;
    return new;
}

const char *bad_array_syntax = "expected number or `]'";

/* allocate memory for a new type object, copy the current type in there, then
 * set up the derivation field on the new type object to point to it. also sets
 * the new top type accordingly */
#define DERIVE_TYPE(t, f) {\
    other_type = dup_type(type);\
    type->top_type = t;\
    type->type.f.derivation = other_type;\
}
/* derive an array type, parse its length, and ensure a closing bracket follows
 */
#define PARSE_ARRAY(b) {\
    DERIVE_TYPE(TOP_ARRAY, array_type);\
    type->type.array_type.length = parse_number(state, &t, b);\
    type->size = other_type->size * type->type.array_type.length;\
    if (!lex(state, &t) || t.kind != T_CLOSE_BRACKET)\
        lex_error(state, bad_array_syntax);\
}

/* parse a type signature. this code is very wacky, just like c type signatures
 * TODO: explain type signature syntax
 */
static char *read_type_signature(struct lex_state *state, struct type *type) {
    struct token t;
    struct type *other_type;
    char *type_name = NULL;
    unsigned char const_qualified = 0;
    unsigned char volatile_qualified = 0;

    if (!parse_standard_type(state, type))
        return NULL;

    while (1) {
        if (!lex(state, &t))
            return NULL;

        switch (t.kind) {
            case T_ASTERISK:
                DERIVE_TYPE(TOP_POINTER, pointer_type);
                const_qualified = 0;
                volatile_qualified = 0;
                type->size = 2;
                break;
            case T_CONST:
                if (const_qualified)
                    lex_error(state, dup_type_qual_err);
                else
                    const_qualified = 1;
                break;
            case T_VOLATILE:
                if (volatile_qualified)
                    lex_error(state, dup_type_qual_err);
                else
                    volatile_qualified = 1;
                break;
            case T_IDENT:
                if (type->top_type == TOP_POINTER) {
                    /* handle qualifiers for the pointer variable itself (not
                     * the type it's pointing to)
                     * this is why const char * and char *const are different */
                    type->type.pointer_type.const_qualified = const_qualified;
                    type->type.pointer_type.volatile_qualified =
                        volatile_qualified;
                }

                type_name = token_to_string(state, &t);

                /* try to parse either an array or [] pointer notation */
                if (!lex(state, &t))
                    return type_name;

                if (t.kind != T_OPEN_BRACKET) {
                    lex_rewind(state);
                    return type_name;
                }

                if (!lex(state, &t))
                    lex_error(state, bad_array_syntax);

                switch (t.kind) {
                    case T_NUMBER:
                        PARSE_ARRAY(10);
                        break;
                    case T_HEX_NUMBER:
                        PARSE_ARRAY(16);
                        break;
                    case T_OCT_NUMBER:
                        PARSE_ARRAY(8);
                        break;
                    case T_CLOSE_BRACKET:
                        /* [] is parsed just like a pointer */
                        DERIVE_TYPE(TOP_POINTER, pointer_type);
                        const_qualified = 0;
                        volatile_qualified = 0;
                        type->size = 2;
                        break;
                    default:
                        lex_error(state, bad_array_syntax);
                }

                return type_name;
            case T_OPEN_BRACKET:
                /* TODO: set type and parse array syntax without setting type
                 * name
                 * code here can probably be similar to array parsing above,
                 * just need to figure out how unnnamed types are handled */
                lex_error(state, "unimplemented");
            default:
                /* rewind the lexer to pass this token back to whatever called
                 * this function */
                lex_rewind(state);

                /* TODO: figure out how to handle nameless types */
                return NULL;
        }
    }

    return type_name;
}

const char *unfinished_struct_union_def = "expected type or `}'";
const char *expected_semicolon = "expected `;'";
const char *duplicate_field = "field with this name was already declared";
const char *unknown_size = "storage size of field is unknown";

/* parse a struct or union definition */
static struct struct_union_field *parse_struct_union(struct lex_state *state) {
    struct struct_union_field *first = NULL;
    unsigned int offset = 0;

    while (1) {
        char *name;
        struct type type;
        struct token t;

        if ((name = read_type_signature(state, &type)) != NULL) {
            unsigned long hash_value;

            if (type.size == 0)
                lex_error(state, unknown_size);

            if (!lex(state, &t) || t.kind != T_SEMICOLON)
                lex_error(state, expected_semicolon);

            hash_string(name, &hash_value);

            if (first == NULL) {
                first = (struct struct_union_field *)
                    malloc(sizeof(struct struct_union_field));
                if (first == NULL) {
                    perror("failed to allocate memory");
                    exit(1);
                }
                first->type = type;
                first->name = name;
                first->name_hash = hash_value;
                first->offset = offset;
                first->next = NULL;
            } else {
                struct struct_union_field *cur = first;

                /* walking the entire list to check hash values probably isn't
                 * the best idea but it should work fine */
                while (1) {
                    if (cur->name_hash == hash_value && strcmp(name, cur->name)
                        == 0)
                        lex_error(state, duplicate_field);
                    else if (cur->next == NULL) {
                        struct struct_union_field *field =
                            (struct struct_union_field *)
                            malloc(sizeof(struct struct_union_field));
                        if (first == NULL) {
                            perror("failed to allocate memory");
                            exit(1);
                        }
                        field->type = type;
                        field->name = name;
                        field->name_hash = hash_value;
                        field->offset = offset;
                        field->next = NULL;
                        cur->next = field;
                        break;
                    }
                    cur = cur->next;
                }
            }

            offset += type.size;
        } else if (!lex(state, &t) || t.kind != T_CLOSE_CURLY)
            lex_error(state, unfinished_struct_union_def);
        else
            break;
    }

    return first;
}

#if 0
static enum type read_type_signature(struct lex_state *state) {
    struct token t;

    if (!lex(state, &t))
        lex_error(state, "expected type signature");

    switch (t.kind) {
        case T_INT:
            return TY_INT;
        default:
            return TY_UNKNOWN;
    }
}

/* parses a semicolon-terminated statement */
static int parse_statement(struct lex_state *state, struct token *first) {
    struct token t;

    switch (first->kind) {
        case T_IDENT:
            lex_error(state, "TODO: ident support");
        case T_SEMICOLON:
            return 1;
        case T_RETURN:
            if (!lex(state, &t) || t.kind != T_NUMBER)
                lex_error(state, "expected number");
            break;
        default:
            lex_error(state, "expected identifier or semicolon");
    }

    if (!lex(state, &t) || t.kind != T_SEMICOLON)
        lex_error(state, "expected semicolon");
}

/* parses a block of code enclosed by curly brackets */
static int parse_block(struct lex_state *state) {
    struct token t;

    if (!lex(state, &t) || t.kind != T_OPEN_CURLY)
        lex_error(state, "expected `{'");

    while (1) {
        if (!lex(state, &t))
            lex_error(state, "unexpected eof");

        switch (t.kind) {
            case T_CLOSE_CURLY:
                return 1;
            default:
                parse_statement(state, &t);
                break;
        }
    }
}

/* parses the arguments and body of a function */
static int parse_function(struct lex_state *state) {
    struct token t;

    /* arguments aren't supported yet */
    if (!lex(state, &t) || t.kind != T_CLOSE_PAREN)
        lex_error(state, "arguments aren't supported yet");

    return parse_block(state);
}
#endif

int parse(struct lex_state *state) {
    struct type uwu;
    struct token t;
    if (!read_type_signature(state, &uwu))
        lex_error(state, "expected type signature");
    printf("size is %d\n", uwu.size);
    if (!lex(state, &t))
        lex_error(state, "unexpected eof");
    printf("next token is %d\n", t.kind);
    if (lex(state, &t))
        printf("next token is %d\n", t.kind);
    else
        printf("nothing after\n");
    return 1;

    /*enum type sig;
    struct token name, t;

    if (!(sig = read_type_signature(state)))
        lex_error(state, "expected type signature");

    if (!lex(state, &t) || t.kind != T_IDENT)
        lex_error(state, "expected identifier, not keyword");

    if (!lex(state, &t))
        lex_error(state, "unexpected eof");

    switch (t.kind) {
        case T_OPEN_PAREN:
            return parse_function(state);
            break;
        default:
            lex_error(state, "unexpected token");
    }*/
}
