CFLAGS += -O2 -I$(PROJECT_ROOT)/core/include -I$(PROJECT_ROOT)/test/include -DUNDER_TEST -DDEBUG
ARFLAGS += --thin
SOURCE_FILES != find . -name "*.c" 2>/dev/null
OBJECTS = $(SOURCE_FILES:.c=.o)
LIBRARY = userland_low_level

.include "$(PROJECT_ROOT)/makefiles/library.mk"
