opcodes = 'HLT NOP SF RF EI DI SLC RLC CL RSR RI RIM ELO PCX DLY RSYS BLC BNL BF BNF BZ BNZ BM BP BGZ BLE BS1 BS2 BS3 BS4 BIE BEP INR DCR CLR IVR SRR SLR RRR RLR ADD SUB AND ORI ORE XFR JSYS LDCC STCC JMP MULU DIVU JSR PUSH POP LD ST WPF RPF WPF1 RPF1 WPFH RPFH LDDMAA STDMAA LDDMAC STDMAC STDMAM EDMA DDMA LDMAMAP SDMAMAP ADDBIG SUBBIG CMPBIG XFRBIG NEGBIG MULBIG DIVBIG DIVBIGR IBASECONV OBASECONV BINLD CONDCPY MEMCPY MEMCMP MEMSET MOV16';

console.log(opcodes.split(' ').map(s => s.split('').map(c => '[' + c.toLowerCase() + c.toUpperCase() + ']').join('') + ' return ' + s + ';').join('\n'));
